Repository BuddiesOfBudgie/budgie-desktop, pull requests merged in 2022-12, with the labels that each got.

#207 Use idle and menu popup to display a Wnck ActionMenu
  src/daemon/menus.vala
Labels: bug

#234 Check for existence of desktop-directories dir in appindexer
  src/appindexer/AppIndex.vala
Labels: bug

#230 Update workspace item icons when window icon changes
  src/applets/workspaces/WindowIcon.vala
Labels: bug

#124 Introduce our native screenshot capability.
  .github/workflows/build.yml
  data/budgie-screenshot.1
  data/meson.build
  meson.build
  src/applets/icon-tasklist/IconButton.vala
  src/applets/icon-tasklist/IconPopover.vala
  src/daemon/aftershot.ui
  src/daemon/budgie-daemon.gresource.xml
  src/daemon/icons/clipboard-shot-symbolic.svg
  src/daemon/icons/edit-shot-symbolic.svg
  src/daemon/icons/org.buddiesofbudgie.BudgieScreenshot.svg
  src/daemon/icons/save-shot-symbolic.svg
  src/daemon/icons/saveshot-noaccess-symbolic.svg
  src/daemon/icons/selectscreen-symbolic.svg
  src/daemon/icons/selectselection-symbolic.svg
  src/daemon/icons/selectwindow-symbolic.svg
  src/daemon/icons/shootscreen-symbolic.svg
  src/daemon/icons/trash-shot-symbolic.svg
  src/daemon/manager.vala
  src/daemon/meson.build
  src/daemon/org.buddiesofbudgie.BudgieScreenshot.desktop.in
  src/daemon/org.buddiesofbudgie.budgie-desktop.screenshot.gschema.xml
  src/daemon/screenshot.vala
  src/daemon/screenshot_main.vala
  src/daemon/screenshothome.ui
  src/wm/com.solus-project.budgie.wm.gschema.xml
  src/wm/meson.build
  src/wm/screenshot.vala
  src/wm/shim.vala
  src/wm/wm.vala
  vapi/mutter-clutter-9.vapi
Labels: enhancement

#235 Add Meson options to allow building on OpenBSD
  meson.build
  meson_options.txt
  src/applets/status/BluetoothIndicator.vala
  src/applets/status/meson.build
  src/panel/uuid.vala
Labels: enhancement

#242 Queue resize of workspace item after size mult changed
  src/applets/workspaces/WorkspacesApplet.vala
Labels: bug

#241 Switch from string parsing to enum values for workspace item size
  src/applets/workspaces/WorkspacesApplet.vala
  src/applets/workspaces/com.solus-project.workspaces.gschema.xml
Labels: bug

#243 Ensure screenshot man-page reflects revised usr/bin binary name
  data/meson.build
  data/org.buddiesofbudgie.BudgieScreenshot.1
Labels: documentation
