Repository BuddiesOfBudgie/budgie-desktop, pull requests merged in 2023-09, with the labels that each got.

#438 Work around more SN/dbusmenu quirks
  src/panel/applets/tray/DBusMenu.vala
  src/panel/applets/tray/DBusMenuNode.vala
  src/panel/applets/tray/TrayItem.vala
Labels: bug

#443 Add xdg-desktop-portal config
  data/budgie-portals.conf
  data/meson.build
Labels: enhancement

#439 Take keywords and generic name into account for relevancy
  src/appindexer/RelevancyService.vala
Labels: enhancement

#444 Make dark theme switch apply to color scheme pref
  src/daemon/settings.vala
Labels: enhancement, accepted

#442 Add setting for tray icon scaling
  src/panel/applets/tray/TrayApplet.vala
  src/panel/applets/tray/com.solus-project.tray.gschema.xml
  src/panel/applets/tray/settings.ui
Labels: enhancement

#455 Attempt to unbox primitives for DBusMenu nodes
  src/panel/applets/tray/DBusMenuNode.vala
Labels: bug

#452 Simplify Raven notification group
  src/daemon/notifications/popup.vala
  src/lib/notification.vala
  src/panel/com.solus-project.budgie-panel.gschema.xml
  src/raven/notifications_group.vala
  src/raven/notifications_view.vala
  src/theme/common/_raven.scss
Labels: enhancement
